"use client";

import { useState } from "react";

type Narrative = {
  body: string;
  source_method: string;
  generated_at: string;
  age_minutes: number;
  is_fresh: boolean;
};

type Props = {
  initial: Narrative | null;
  accessToken: string;
};

function backendUrl(): string {
  const raw = process.env.NEXT_PUBLIC_BACKEND_URL || "";
  return raw.replace(/\/$/, "");
}

function relativeTime(generatedAt: string): string {
  const then = new Date(generatedAt);
  if (Number.isNaN(then.getTime())) return "just now";
  const diffMs = Date.now() - then.getTime();
  const minutes = Math.round(diffMs / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes} min ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours} hr ago`;
  const days = Math.round(hours / 24);
  return `${days} d ago`;
}

export function WeeklyNarrative({ initial, accessToken }: Props) {
  const [narrative, setNarrative] = useState<Narrative | null>(initial);
  const [refreshing, setRefreshing] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const onRefresh = async () => {
    if (refreshing) return;
    const base = backendUrl();
    if (!base) {
      setError("NEXT_PUBLIC_BACKEND_URL is not configured.");
      return;
    }
    setRefreshing(true);
    setError(null);
    try {
      const response = await fetch(`${base}/dashboard/narrative/refresh`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
      });
      if (!response.ok) {
        const text = await response.text();
        let message = text || `Refresh failed (${response.status})`;
        try {
          const errPayload = JSON.parse(text) as { detail?: string; error?: string };
          message = errPayload.detail || errPayload.error || message;
        } catch {
          // ignore
        }
        throw new Error(message);
      }
      const result = (await response.json()) as { data: Narrative };
      setNarrative(result.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not refresh narrative.");
    } finally {
      setRefreshing(false);
    }
  };

  const sourceTag =
    narrative?.source_method === "gemini" ? "Generated by Gemini" : "Local fallback";
  const showWarning = narrative && narrative.source_method !== "gemini";

  return (
    <section className="zen-card zen-narrative-card">
      <div className="zen-narrative-head">
        <span className="zen-chip">This Fortnight</span>
        <button
          type="button"
          className="zen-button-ghost"
          onClick={onRefresh}
          disabled={refreshing}
          aria-label="Regenerate the narrative"
        >
          {refreshing ? "Refreshing…" : "Refresh"}
        </button>
      </div>

      {narrative ? (
        <blockquote className="zen-narrative-body">
          <p>{narrative.body}</p>
        </blockquote>
      ) : (
        <p className="zen-note" style={{ margin: "10px 0" }}>
          The narrative card will appear once a few check-ins have been recorded.
        </p>
      )}

      <div className="zen-narrative-meta">
        {narrative ? (
          <>
            <span className="zen-narrative-meta-source" title={sourceTag}>
              {narrative.source_method === "gemini" ? "✦ Gemini" : "○ fallback"}
            </span>
            <span aria-hidden="true">·</span>
            <span>{relativeTime(narrative.generated_at)}</span>
          </>
        ) : null}
        {showWarning ? (
          <span
            className="zen-narrative-meta-warn"
            title="Gemini was unavailable when this was generated. Click Refresh to try again."
          >
            (refresh to try Gemini)
          </span>
        ) : null}
      </div>

      {error ? (
        <p className="zen-error" role="alert" style={{ marginTop: 6 }}>
          {error}
        </p>
      ) : null}
    </section>
  );
}
